### ISSUE TITLE
Difference between CoAPthon and txThings

### ISSUE THREAD

**Issue by Venkat2811** [mwasilak/txThings#17]
Hi,

Could you explain the difference between txThings and CoAPthon ?

Thanks,
Venkat

**Comment by mwasilak** [comment]
Hi,

I have no experience with CoAPthon - it seems to be a general purpose library, not attached to any particular framework. It also has a branch for Twisted, but it's not native (doesn't use deferreds etc.). It seems to be maintained. I can't comment on its capabilities.

TxThings is a library for Twisted framework only, it extensively uses deferreds, and requires them for writing clients and (non-basic) servers. It's not actively maintained.

If your project is going to use Twisted, and you understand its abstractions well (especially deferred chaining), then using txThings may have some nice advantages for you. For non-Twisted projects it's better to start with CoAPthon.

**Comment by Venkat2811** [comment]
Hi @mwasilak 

Thanks for explaining. 

Thanks,
Venkat
